site_name: Pysparta Documentation
theme:
  name: material  # El mejor tema para documentación técnica
  features:
    - content.code.copy # Botón para copiar código
    - navigation.sections
  palette: 
    # Esquema para Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Esquema para Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Getting Started:
      - Installation: installation.md
      - Configuration: configuration.md
      - Logging & Debugging: logging.md
  - Science & Models:
      - About the Models: models.md
      - Atmospheric Databases: atmosphere.md
  - API Reference:
      - Main Interface: api/main.md
      - Clear-Sky Models: api/models.md
      - Atmospheric Data: api/crsdata.md
      - Utilities & Validators: api/utils.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # Esto permite que los tipos de pandas/python tengan links:
          inventories:
            - https://docs.python.org/3/objects.inv
            - http://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://docs.xarray.dev/en/stable/objects.inv
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.arithmatex: # Para las ecuaciones LaTeX
      generic: true
  - pymdownx.superfences: # Para bloques de código y diagramas
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details: # Para que los "Notes" o "Examples" se puedan colapsar
  - attr_list: # Para iconos y estilos extra
